### ISSUE TITLE
Lightning Talk Submission - KeyPaths

### ISSUE THREAD

**Issue by AJ9** [NSManchester/nsmanchester-talks#7]
Submitted for the Lightning talks on March 4, 2019: https://www.meetup.com/NSManchester/events/gkzcqqyzfbgb/

Short description:

A quick overview of what KeyPaths are and how they can be used to make code more readable and concise. This talk will show practical examples of typical code (such as sorting and filtering) and how they can be converted to use KeyPaths instead.  

Unable to select a label to assign to this so, please assign/assume this to be `Talk Volunteered`

**Comment by Winnie90** [comment]
Hi Adam,

Sorry for the really late reply, I didn't think anyone had found the issue stuff and didn't have notifications setup 🤦‍♂ 
Still sounds like a great talk if you'd like to give it, we can do lightning talks at July's meetup or there is still a slot if you want to turn it into a longer 20 minute or so talk.

Thanks

Chris
