### ISSUE TITLE
Talk Volunteered - Flutter: the Good, the Bad and the Ugly

### ISSUE THREAD

**Issue by jackhllns** [NSManchester/nsmanchester-talks#8]
Quick overview:

A short talk giving a quick overview of how we have been experimenting with Flutter and what we have learned about it

**Comment by Winnie90** [comment]
Hi Jack,

Sorry for the late reply, I didn't think anyone had found the issue stuff and didn't have notifications setup 🤦‍♂
Would be great to hear about Flutter, sounds really interesting, we have the Keynote watch party next week, would you be free to give the talk at July's meetup?

Thanks

Chris

**Comment by jackhllns** [comment]
Hi Chris,

Yep, July sounds good to me!

**Comment by Winnie90** [comment]
Great I'll add you to the program.
